/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Yasmim Mendes
 */

import javax.swing.JOptionPane;
import model.ExercicioModel;
import controller.ExercicioController;
import model.EquipamentoModel;
import controller.EquipamentoController;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;


public class ExercicioView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ExercicioView.class.getName());

    /**
     * Creates new form ExercicioView
     */
    public ExercicioView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jlCodigoFicha = new javax.swing.JLabel();
        jtxId_Exercicio = new javax.swing.JTextField();
        jbPesquisar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jtxNome = new javax.swing.JTextField();
        jbNovo = new javax.swing.JButton();
        jbSalvar = new javax.swing.JButton();
        jbEditar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jbFechar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtExercicio = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jcbEquipamento = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jtxGrupoMuscular = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setVisible(true);

        jlCodigoFicha.setText("Código:");

        jbPesquisar.setText("Pesquisar");
        jbPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisarActionPerformed(evt);
            }
        });

        jLabel3.setText("Nome:");

        jbNovo.setText("Novo");
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });

        jbSalvar.setText("Salvar");
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jbEditar.setText("Editar");
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });

        jbExcluir.setText("Excluir");
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jbFechar.setText("Fechar");
        jbFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFecharActionPerformed(evt);
            }
        });

        jtExercicio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Código do Equipamento", "Grupo Muscular"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtExercicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtExercicioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtExercicio);

        jLabel5.setText("Código do equipamento:");

        jcbEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbEquipamentoActionPerformed(evt);
            }
        });

        jLabel4.setText("Grupo Muscular:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jbNovo)
                                .addGap(20, 20, 20)
                                .addComponent(jbSalvar)
                                .addGap(18, 18, 18)
                                .addComponent(jbEditar)
                                .addGap(18, 18, 18)
                                .addComponent(jbExcluir)
                                .addGap(18, 18, 18)
                                .addComponent(jbFechar))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(47, 47, 47)
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jtxGrupoMuscular))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtxNome, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(4, 4, 4)
                                        .addComponent(jcbEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jlCodigoFicha)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtxId_Exercicio, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbPesquisar)))))))
                .addGap(41, 41, 41))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlCodigoFicha)
                        .addComponent(jtxId_Exercicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jcbEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxGrupoMuscular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbNovo)
                    .addComponent(jbSalvar)
                    .addComponent(jbEditar)
                    .addComponent(jbExcluir)
                    .addComponent(jbFechar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jInternalFrame1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisarActionPerformed
        ExercicioModel exercicio = new ExercicioModel();

        if (jtxId_Exercicio.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Preencha o código do exercício!",
                "Retorno Tela", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                exercicio.setIdExercicio(Integer.parseInt(jtxId_Exercicio.getText()));

                ExercicioController controller = new ExercicioController();
                exercicio = controller.selecionar(exercicio);

                if (exercicio == null) {
                    JOptionPane.showMessageDialog(this, "Exercício não encontrado!",
                        "Retorno BD", JOptionPane.ERROR_MESSAGE);
                } else {
                    jcbEquipamento.setSelectedItem(exercicio.getIdEquipamento());

                    jtxNome.setText(exercicio.getNome());
                    jtxGrupoMuscular.setText(exercicio.getGrupoMuscular());

                    jbNovo.setEnabled(false);
                    jbSalvar.setEnabled(false);
                    jbEditar.setEnabled(true);
                    jbExcluir.setEnabled(true);

                    jtxId_Exercicio.setEditable(false);
                    jcbEquipamento.setEnabled(true);
                    jtxNome.setEditable(true);
                    jtxGrupoMuscular.setEditable(true);
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Código inválido!",
                    "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jbPesquisarActionPerformed

    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed
        jbPesquisar.setEnabled(false);
        jbNovo.setEnabled(false);
        jbEditar.setEnabled(false);
        jbExcluir.setEnabled(false);
        jbSalvar.setEnabled(true);

        jtxId_Exercicio.setEditable(false);

        jcbEquipamento.setEnabled(true);
        jtxNome.setEditable(true);
        jtxGrupoMuscular.setEditable(true);

        jtxId_Exercicio.setText("");
        jcbEquipamento.setSelectedIndex(-1);
        jtxNome.setText("");
        jtxGrupoMuscular.setText("");
    }//GEN-LAST:event_jbNovoActionPerformed

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        Object equipamentoSelecionado = jcbEquipamento.getSelectedItem();
        String nome = jtxNome.getText();
        String grupoMuscular = jtxGrupoMuscular.getText();

        if (equipamentoSelecionado == null || nome.isEmpty() || grupoMuscular.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Preencha todos os campos!",
                "Retorno Tela", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            EquipamentoModel equipamento = (EquipamentoModel) equipamentoSelecionado;

            ExercicioModel exercicio = new ExercicioModel();
            exercicio.setIdEquipamento(equipamento);
            exercicio.setNome(nome);
            exercicio.setGrupoMuscular(grupoMuscular);

            ExercicioController controller = new ExercicioController();
            if (controller.inserir(exercicio)) {
                JOptionPane.showMessageDialog(this, "Exercício inserido com sucesso!");
                limparCampos();
                inicializa();
                preencherTabela();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao inserir o exercício!",
                    "Retorno BD", JOptionPane.ERROR_MESSAGE);
            }
        } catch (ClassCastException e) {
            JOptionPane.showMessageDialog(this, "Erro no tipo dos dados selecionados no combo.",
                "Erro de Dados", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed
        try {
            int idExercicio = Integer.parseInt(jtxId_Exercicio.getText());
            Object equipamentoSelecionado = jcbEquipamento.getSelectedItem();
            String nome = jtxNome.getText();
            String grupoMuscular = jtxGrupoMuscular.getText();

            if (equipamentoSelecionado == null || nome.isEmpty() || grupoMuscular.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Preencha todos os campos!",
                    "Retorno Tela", JOptionPane.ERROR_MESSAGE);
                return;
            }

            EquipamentoModel equipamento = (EquipamentoModel) equipamentoSelecionado;

            ExercicioModel exercicio = new ExercicioModel();
            exercicio.setIdExercicio(idExercicio);
            exercicio.setIdEquipamento(equipamento);
            exercicio.setNome(nome);
            exercicio.setGrupoMuscular(grupoMuscular);

            ExercicioController controller = new ExercicioController();
            if (controller.editar(exercicio)) {
                JOptionPane.showMessageDialog(this, "Exercício atualizado com sucesso!");
                limparCampos();
                inicializa();
                preencherTabela();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao editar exercício!",
                    "Retorno BD", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ID do exercício inválido!",
                "Erro", JOptionPane.ERROR_MESSAGE);
        } catch (ClassCastException e) {
            JOptionPane.showMessageDialog(this, "Erro no tipo dos dados selecionados no combo.",
                "Erro de Dados", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbEditarActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        if (jtxId_Exercicio.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite o código do exercício!",
                "Retorno Tela", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                int idExercicio = Integer.parseInt(jtxId_Exercicio.getText());

                ExercicioModel exercicio = new ExercicioModel();
                exercicio.setIdExercicio(idExercicio);

                ExercicioController controller = new ExercicioController();
                if (controller.excluir(exercicio)) {
                    JOptionPane.showMessageDialog(this, "Exercício excluído com sucesso!");
                    limparCampos();
                    inicializa();
                    preencherTabela();
                } else {
                    JOptionPane.showMessageDialog(this, "Erro ao excluir exercício!",
                        "Retorno BD", JOptionPane.ERROR_MESSAGE);
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Código do exercício inválido!",
                    "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jbFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFecharActionPerformed
        dispose();
    }//GEN-LAST:event_jbFecharActionPerformed

    private void jtExercicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtExercicioMouseClicked
        int linha = jtExercicio.getSelectedRow();
        if (linha != -1) {

            jtxId_Exercicio.setText(jtExercicio.getValueAt(linha, 0).toString());

            Integer idEquipamento = Integer.parseInt(jtExercicio.getValueAt(linha, 1).toString());
            jcbEquipamento.setSelectedItem(idEquipamento);

            jtxNome.setText(jtExercicio.getValueAt(linha, 2).toString());
            jtxGrupoMuscular.setText(jtExercicio.getValueAt(linha, 3).toString());

            jbNovo.setEnabled(false);
            jbSalvar.setEnabled(false);
            jbEditar.setEnabled(true);
            jbExcluir.setEnabled(true);

            jtxId_Exercicio.setEditable(false);
            jcbEquipamento.setEnabled(true);
            jtxNome.setEditable(true);
            jtxGrupoMuscular.setEditable(true);
        }
    }//GEN-LAST:event_jtExercicioMouseClicked

    private void jcbEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbEquipamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbEquipamentoActionPerformed

    private void preencherTabela() {
        ExercicioController controller = new ExercicioController();
        ArrayList<ExercicioModel> lista = controller.selecionarTodos();
        DefaultTableModel modeloTabela = (DefaultTableModel) jtExercicio.getModel();
        modeloTabela.setRowCount(0);

        if (lista.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nenhum exercício cadastrado!",
                "Retorno Tela", JOptionPane.ERROR_MESSAGE);
        } else {
            for (ExercicioModel e : lista) {
                modeloTabela.addRow(new Object[] {
                    e.getIdExercicio(),
                    e.getIdEquipamento(),
                    e.getNome(),
                    e.getGrupoMuscular()
                });
            }
        }
    }

    private void inicializa() {
        jtxId_Exercicio.setEditable(true);
        jcbEquipamento.setEnabled(false);
        jtxNome.setEditable(false);
        jtxGrupoMuscular.setEditable(false);

        jbSalvar.setEnabled(false);
        jbEditar.setEnabled(false);
        jbExcluir.setEnabled(false);
        jbPesquisar.setEnabled(true);
        jbNovo.setEnabled(true);
    }

    private void limparCampos() {
        jtxId_Exercicio.setText("");
        jcbEquipamento.setSelectedIndex(-1);
        jtxNome.setText("");
        jtxGrupoMuscular.setText("");
    }

    private void preencherComboBox() {
        EquipamentoController equipamentoController = new EquipamentoController();
        ArrayList<EquipamentoModel> listaEquipamentos = equipamentoController.selecionarTodos();

        jcbEquipamento.removeAllItems();
        for (EquipamentoModel equipamento : listaEquipamentos) {
            jcbEquipamento.addItem(equipamento);
        }
    }

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbFechar;
    private javax.swing.JButton jbNovo;
    private javax.swing.JButton jbPesquisar;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JComboBox<model.EquipamentoModel> jcbEquipamento;
    private javax.swing.JLabel jlCodigoFicha;
    private javax.swing.JTable jtExercicio;
    private javax.swing.JTextField jtxGrupoMuscular;
    private javax.swing.JTextField jtxId_Exercicio;
    private javax.swing.JTextField jtxNome;
    // End of variables declaration//GEN-END:variables
}
